# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: awsapihttp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-api-http

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /
          method: get
  bye:
    handler: bye.handler
    events:
      - httpApi:
          path: /bye
          method: get
